TrainingArguments:
  output_dir: artifacts/model_trainer/phi3-samsum-lora
  evaluation_strategy: epoch
  learning_rate: 0.0002
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  weight_decay: 0.01
  save_total_limit: 3
  num_train_epochs: 1
  predict_with_generate: true
  fp16: true
  gradient_accumulation_steps: 4

LoraArguments:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  bias: none
  task_type: CAUSAL_LM
